spring.application.name=health-habits-api
habits.table=${TABLE_NAME:}
habits.local=false
habits.endpoint=
habits.issuer=${COGNITO_ISSUER}
habits.client-id=${CLIENT_ID}
habits.origin=${WEBSITE_ORIGIN:http://localhost:4200}
server.error.include-message=never
server.error.include-stacktrace=never
spring.main.banner-mode=off
